image: ecr.aws.steedos.cn/dockerhub/steedos/gitpod-workspace-base:2.2.6-node18

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 5000 # Steedos
    onOpen: ignore
    visibility: public
  - port: 3000 # Frontend
    onOpen: ignore
    visibility: public
  - port: 1880 # Node-RED
    onOpen: ignore
    visibility: public
  - port: 6379 # Redis
    onOpen: ignore
  - port: 9001 # Supervisor
    onOpen: ignore
  - port: 27017 # MongoDB
    onOpen: ignore
    
# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Steedos Platform
    init: |
      RANDOM_API_KEY=$(openssl rand -hex 32)
      echo "STEEDOS_INITIAL_API_KEY=$RANDOM_API_KEY" >> steedos-platform/.env.local
      echo "METADATA_APIKEY=$RANDOM_API_KEY" >> .env.local
    command: |
      echo "ROOT_URL=$(gp url 5000)" >> steedos-platform/.env.local

      docker-compose -f steedos-platform/docker-compose.yml up
  - name: Steedos Packages
    command: |
      git config pull.rebase false
      echo "METADATA_SERVER=$(gp url 5000)" >> .env.local
      npm i --verbose
      gp await-port 5000
      npm run dev


vscode:
  extensions:
    - redhat.vscode-yaml
    - steedos.steedosdx-vscode
    - steedos.steedosdx-vscode-core
    - ms-ceintl.vscode-language-pack-zh-hans