image: ecr.aws.steedos.cn/dockerhub/steedos/gitpod-workspace-base:2.2.5

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 5000 # Steedos
    onOpen: ignore
    visibility: public
  - port: 3000 # Frontend
    onOpen: ignore
    visibility: public
  - port: 1880 # Node-RED
    onOpen: ignore
    visibility: public
  - port: 6379 # Redis
    onOpen: ignore
  - port: 9001 # Supervisor
    onOpen: ignore
  - port: 27017 # MongoDB
    onOpen: ignore
    
# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Steedos Platform
    command: |
      echo "ROOT_URL=$(gp url 5000)" >> steedos-platform/.env.local
      docker-compose -f steedos-platform/docker-compose.yml up
  - name: Steedos Packages
    command: |
      echo "METADATA_SERVER=$(gp url 5000)" >> .env.local
      echo "B6_FRONTEND_URL=$(gp url 3000)" >> .env.local
      npm config set registry=https://registry.npmmirror.com
      npm install -g steedos-cli
      yarn
      yarn build
      gp await-port 5000
      yarn start
  - name: Frontend
    command: |
      nvm i 18
      nvm use 18
      yarn
      gp await-port 5000
      echo "AUTH_URL=$(gp url 3000)" >> .env.local
      echo "STEEDOS_ROOT_URL=$(gp url 5000)" >> .env.local
      yarn dev


vscode:
  extensions:
    - redhat.vscode-yaml
    - steedos.steedosdx-vscode
    - steedos.steedosdx-vscode-core
    - ms-ceintl.vscode-language-pack-zh-hans
