version: "3.9"

services:
  builder6:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    image: steedos/builder6:latest
    container_name: builder6
    env_file:
      - .env
      - .env.local
    environment:
      - TRANSPORTER=redis://steedos:6379
    networks:
      - steedos-platform_steedos_network

networks:
  steedos-platform_steedos_network:
    external: true