name: products
create: true
enable_enhanced_lookup: true
enable_thousands: true
filterable: false
generated: false
hidden: false
index: false
is_name: false
is_wide: false
label: 产品
multiple: false
primary: false
readonly: false
reference_to: b6_products
required: false
searchable: false
show_as_qr: false
sort_no: 100
sortable: false
static: false
type: lookup
unique: false
write_requires_master_read: false
