version: "3.9"

services:
  steedos-community:
    image: ecr.aws.steedos.cn/dockerhub/steedos/steedos-community:2.7.1-beta.16
    ports:
      - "5000:3000"    # Steedos
      - "27017:27017"  # MongoDB
      - "9001:9001"    # Supervisor
      - "6379:6379"    # Redis
    env_file:
      - ../.env
      - ../.env.local
    environment:
      - ROOT_URL=https://5000-rose-rhinoceros-u566xbt3.ws.vscode.steedos.cn/
      - TRANSPORTER=redis://redis:6379
      - CACHER=redis://redis:6379/1
    volumes:
      - "./steedos-storage:/steedos-storage"
    depends_on:
      redis:
        condition: service_started
  builder6:
    build: 
      context: ../
      dockerfile: ./docker/Dockerfile
    image: steedos/builder6:latest
    container_name: builder6
    env_file:
      - ../.env
      - ../.env.local
    environment:
      - TRANSPORTER=redis://redis:6379
      - CACHER=redis://redis:6379/1
    depends_on:
      redis:
        condition: service_started
  redis:
    image: ecr.aws.steedos.cn/dockerhub/redis:6.2
    command: "redis-server --save \"\" --appendonly no --loglevel warning"