name: Build and Push Docker Image on Version Change

on:
  push:
    paths:
      - 'version.json'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read docker-version from version.json
        id: read_version
        run: |
          DOCKER_VERSION=$(jq -r .["docker-version"] version.json)
          echo "DOCKER_VERSION=$DOCKER_VERSION" >> $GITHUB_ENV
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_NINGXIA }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_NINGXIA }}
          aws-region: cn-northwest-1
      -
        name: Login to ECR
        uses: docker/login-action@v2
        with:
          registry: 252208178451.dkr.ecr.cn-northwest-1.amazonaws.com.cn

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            steedos/builder6
            252208178451.dkr.ecr.cn-northwest-1.amazonaws.com.cn/dockerhub/steedos/builder6

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            steedos/builder6:${{ env.DOCKER_VERSION }}
            252208178451.dkr.ecr.cn-northwest-1.amazonaws.com.cn/dockerhub/steedos/builder6:${{ env.DOCKER_VERSION }}
          no-cache: true

      - name: Log out from Docker Hub
        run: docker logout