name: Build and Push Docker Image on Tag

on:
  push:
    tags:
      - 'v*'  # 仅在创建标签时触发，例如 v1.0, v2.1.0 等

jobs:
  update-from-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: sync-branch-docker-fssh
        uses: wei/git-sync@v3
        with:
          source_repo: https://${{secrets.ADMIN_ACCOUNT_GITLAB}}:${{secrets.ADMIN_PASSWORD_GITLAB}}@gitlab.steedos.cn/steedos/builder6
          source_branch: "refs/remotes/source/*"
          destination_repo: https://${{secrets.ADMIN_ACCOUNT_GITHUB}}:${{secrets.ADMIN_PASSWORD_GITHUB}}@github.com/steedos/builder6
          destination_branch: "refs/heads/*"
  
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_NINGXIA }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_NINGXIA }}
          aws-region: cn-northwest-1
      -
        name: Login to ECR
        uses: docker/login-action@v2
        with:
          registry: 252208178451.dkr.ecr.cn-northwest-1.amazonaws.com.cn

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            steedos/builder6
            252208178451.dkr.ecr.cn-northwest-1.amazonaws.com.cn/dockerhub/steedos/builder6

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            steedos/builder6:${{ env.VERSION }}
            252208178451.dkr.ecr.cn-northwest-1.amazonaws.com.cn/dockerhub/steedos/builder6:${{ env.VERSION }}

      - name: Log out from Docker Hub
        run: docker logout